options:
  ssl_enabled:
    type: boolean
    default: False
    description: enable SSL
  management_plugin:
    type: boolean
    default: False
    description: enable the management plugin
  ssl_port:
    type: int
    default: 5671
    description: SSL port
  ssl_key:
    type: string
    description: private unencrypted key in PEM format (starts "-----BEGIN RSA PRIVATE KEY-----")
    default: ""
  ssl_cert:
    type: string
    description: X.509 certificate in PEM format (starts "-----BEGIN CERTIFICATE-----")
    default: ""
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  # HA configuration settings
  vip:
      type: string
      description: "Virtual IP to use to front rabbitmq in ha configuration"
      default: ""
  vip_iface:
      type: string
      default: eth0
      description: "Network Interface where to place the Virtual IP"
  vip_cidr:
      type: int
      default: 24
      description: "Netmask that will be used for the Virtual IP"
  ha-bindiface:
      type: string
      default: eth0
      description: |
        Default network interface on which HA cluster will bind to communication
        with the other members of the HA Cluster.
  ha-mcastport:
      type: int
      default: 5406
      description: |
        Default multicast port number that will be used to communicate between
        HA Cluster nodes.
  ha-vip-only:
      type: boolean
      default: False
      descriptions: |
        By default, without pairing with hacluster charm, rabbitmq will deploy
        in active/active/active... HA. When pairied with hacluster charm, it
        will deploy as active/passive. By enabling this option, pairing with
        hacluster charm will keep rabbit in active/active setup, but in addition
        it will deploy a VIP that can be used by services that cannot work
        with mutiple AMQPs (like Glance in pre-Icehouse).
  rbd-size:
      type: string
      default: 5G
      description: |
        Default rbd storage size to create when setting up block storage.
        This value should be specified in GB (e.g. 100G).
  rbd-name:
      type: string
      default: rabbitmq1
      description: |
        The name that will be used to create the Ceph's RBD image with. If the
        image name exists in Ceph, it will be re-used and the data will be
        overwritten.
  max-cluster-tries:
      type: int
      default: 3
      description: |
        Number of tries to cluster with other units before giving up.
        If errors clustering happening in more than these units, charm will
        end with an error
  install_sources:
      type: string
      default: ""
      description: |
        Repository from which to install.  May be one of the following:
        distro (default), ppa:somecustom/ppa, a deb url sources entry,
        or a supported Cloud Archive release pocket.

        Supported Cloud Archive sources include: cloud:precise-folsom,
        cloud:precise-folsom/updates, cloud:precise-folsom/staging,
        cloud:precise-folsom/proposed. Also, a list is supported:
        # install_sources:
        #   - "ppa:foo"
        #   - "http://example.com/repo precise main"
        # install_keys:
        #   - null
        #   - "a1b2c3d4"
  install_keys:
      type: string
      description: |
        PGP keys to be installed with install_sources
