options:
  ssl_enabled:
    type: boolean
    default: False
    description: enable SSL
  management_plugin:
    type: boolean
    default: False
    description: enable the management plugin
  ssl_port:
    type: int
    default: 5671
    description: SSL port
  ssl_key:
    type: string
    description: private unencrypted key in PEM format (starts "-----BEGIN RSA PRIVATE KEY-----")
  ssl_cert:
    type: string
    description: X.509 certificate in PEM format (starts "-----BEGIN CERTIFICATE-----")
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
