options:
  ssl_enabled:
    type: boolean
    default: False
    description: enable SSL
  management_plugin:
    type: boolean
    default: False
    description: enable the management plugin
  ssl_port:
    type: int
    default: 5671
    description: SSL port
  ssl_key:
    type: string
    description: private unencrypted key in PEM format (starts "-----BEGIN RSA PRIVATE KEY-----")
  ssl_cert:
    type: string
    description: X.509 certificate in PEM format (starts "-----BEGIN CERTIFICATE-----")
  # HA configuration settings
  vip:
      type: string
      description: "Virtual IP to use to front rabbitmq in ha configuration"
  vip_iface:
      type: string
      default: eth0
      description: "Network Interface where to place the Virtual IP"
  vip_cidr:
      type: int
      default: 24
      description: "Netmask that will be used for the Virtual IP"
  ha-bindiface:
      type: string
      default: eth0
      description: |
        Default network interface on which HA cluster will bind to communication
        with the other members of the HA Cluster.
  ha-mcastport:
      type: int
      default: 5407
      description: |
        Default multicast port number that will be used to communicate between
        HA Cluster nodes.

